#!/bin/bash

COMMAND=$1
# DOMAIN=$2
# FORWARD_TO_PORT=$3
REPETERDIR=$(echo $PWD)

source ./src/helpers.sh
source ./src/help.sh
source ./src/init.sh
source ./src/pulumi_down.sh
source ./src/pulumi_up.sh
source ./src/pulumi_destroy.sh
source ./src/status.sh
source ./src/tunnel_down.sh
source ./src/tunnel_up.sh
