#!/bin/bash

COMMAND=$1
# DOMAIN=$2
# FORWARD_TO_PORT=$3
REPETERDIR=$(echo $PWD)

if [ $# -eq 0 ]; then
    $REPETERDIR/repeter help
    exit 1
fi

source $REPETERDIR/src/helpers.sh
source $REPETERDIR/src/help.sh
source $REPETERDIR/src/init.sh
source $REPETERDIR/src/pulumi_down.sh
source $REPETERDIR/src/pulumi_up.sh
source $REPETERDIR/src/pulumi_destroy.sh
source $REPETERDIR/src/status.sh
source $REPETERDIR/src/tunnel_down.sh
source $REPETERDIR/src/tunnel_up.sh
